title: Globoesporte
email: gabriel.globoesporte@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Site dos desenvolvedores do Globoesporte
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://globoesporte.github.io"
assetspath: http://localhost:3000/
repository: globoesporte/globoesporte.github.io

source: src
destination: dist

# Build settings
markdown: kramdown
permalink: /:title/

kramdown:
    syntax_highlighter_opts:
        disable: true

gems: []

exclude: ['node_modules', 'yarn.lock', 'assets/layout', 'package.json', 'assets/_styl', 'vendor/bundle/ruby', 'assets/*.js', 'assets/js/**/*.js', 'assets/js/*.js', '*.hot-update.json', '_site/*.hot-update.json', 'npm-debug.log', 'webpack.config.dev.js', 'webpack.config.prod.js', 'README.md']

keep_files: ['assets/bundle.app.js']

incremental: true
