title: Globoesporte
email: gabriel.globoesporte@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am passionated about the web and for new technologies. There is nothing more dynamic than the web, and that is why learning new things becomes a daily habit for me.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://globoesporte.github.io" # the base hostname & protocol for your site
twitter_username: globoesporte
github_username:  globoesporte

# Build settings
markdown: kramdown
permalink: /:title/

kramdown:
    syntax_highlighter_opts:
        disable: true

include:
  - node_modules

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

links:
  - title: blog
    url: /blog
  - title: sobre
    url: /sobre
  - title: Tags
    url: /tags

gems: []

mermaid:
  src: 'https://cdn.rawgit.com/knsv/mermaid/6.0.0/dist/mermaid.min.js'

exclude: ['package.json', 'src', 'node_modules', 'vendor/bundle/ruby', 'gulpfile.js']
