title: Globoesporte
email: gabriel.globoesporte@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Site dos desenvolvedores do Globoesporte
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://globoesporte.github.io" # the base hostname & protocol for your site
twitter_username: globoesporte
github_username:  globoesporte

# Build settings
markdown: kramdown
permalink: /:title/

kramdown:
    syntax_highlighter_opts:
        disable: true

include:
  - node_modules

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

gems: []

exclude: ['package.json', 'src', 'node_modules', 'vendor/bundle/ruby', 'gulpfile.js', 'assets/js/**/*.js', 'assets/js/main.js']
